// ExceptionStandard.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
33include exception

int main()
{
   
}
